<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>FaceAiSharp.FaceONNX</PackageId>
    <RootNamespace>FaceAiSharp</RootNamespace>
    <AssemblyName>FaceAiSharp.FaceONNX</AssemblyName>
    <Authors>Georg Jung</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FaceONNX" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FaceAiSharp\FaceAiSharp.csproj" />
  </ItemGroup>

</Project>
