name: CI

on:
  workflow_call:
    inputs:
      build-ref:
        required: true
        type: string
  workflow_dispatch:
  push:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        lfs: true
    - uses: dotnet/nbgv@v0.4
      id: nbgv
    - run: dotnet restore /p:ContinuousIntegrationBuild=true
    - run: dotnet build -c Release --no-restore /p:ContinuousIntegrationBuild=true
    - run: >-
        dotnet test
        -c Release --no-restore --no-build
        /p:ContinuousIntegrationBuild=true
        /p:CoverletOutputFormat=\"opencover,cobertura\"
        -s CodeCoverage.runsettings
        --collect:"XPlat Code Coverage"
        --logger "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true"
        --
        RunConfiguration.CollectSourceInformation=true
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@v5
      with:
        reports: "**/coverage.cobertura.xml"
        targetdir: coveragereport
        license: ${{ secrets.ReportGeneratorLicense }}
    - uses: actions/upload-artifact@v4
      with:
        name: CoverageReport-${{ steps.nbgv.outputs.Version }}
        path: coveragereport
    - name: Upload coverage reports to Codecov
      if: ${{ env.CODECOV_TOKEN }}
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        slug: georg-jung/FaceAiSharp
    - run: dotnet pack -c Release --no-restore --no-build /p:ContinuousIntegrationBuild=true
    - uses: actions/upload-artifact@v4
      with:
        name: nupkg
        path: bin/Packages/Release/**/*
